### ISSUE TITLE
Indy Node system tests depend on the Sovrin package

### ISSUE THREAD

**Issue by askolesov** [hyperledger/indy-test-automation#102]
That's bad because if someone makes breaking changes in Node, he has to release an updated version of Sovrin in order to fix and run tests.

Example of depending code:
https://github.com/hyperledger/indy-test-automation/blob/master/system/docker/node/Dockerfile#L65

Proposal:
* Make a Sovrin fork of this repository.
* Get rid of Sovrin dependencies and tests in this repository.
* When new changes are added to this repository, merge them into the fork.
* Keep everything Sovrin specific in the fork.

This PR was intended to fix it but I didn't have time to accomplish it so it's closed:
https://github.com/hyperledger/indy-test-automation/pull/101

This proposal is the result of the previous research.

**Comment by WadeBarnes** [comment]
## Additional details on the circular dependency:
- `indy-test-automation` references `sovrin` package dependencies which in turn reference a specific `indy-node` package.  Therefore, currently, to test a specific `indy-node` release a `sovrin` package referencing that specific release needs to be made.
- This circular dependency needs to be broken.  The code needs to be updated in such a way that `indy-node` releases and `indy-node` based releases (such as `sovrin`) can be tested separately.

## The way forward:
- Although forking the repo and making updates to the two forks would work, I don't think it's the best approach.  I'm of the opinion `indy-test-automation` should be updated to generically support any `indy-node` based release.
  - Both @askolesov and @devinleighsmith started down this path with the following PRs:
    - https://github.com/hyperledger/indy-test-automation/pull/101
    - https://github.com/hyperledger/indy-test-automation/pull/103 - Based on Alex's PRs
    - https://github.com/hyperledger/indy-test-automation/pull/104
    - https://github.com/hyperledger/indy-test-automation/pull/106

Unfortunately this code does not work to conditionally install `sovrin`:
https://github.com/hyperledger/indy-test-automation/blob/3b44feb9bc6ead49c7e8ed16d2199c23dc78d187/system/docker/node/Dockerfile#L65-L67

and which had yet to also address conditional installation of the `token-plugin` which also references a specific version of `indy-node`:
https://github.com/hyperledger/indy-test-automation/blob/3b44feb9bc6ead49c7e8ed16d2199c23dc78d187/system/docker/node/Dockerfile#L69-L78 

## Important details:
- `indy-test-automation` relies on docker-in-docker to spin up the nodes it uses for testing. If that's not configured properly things don't work.  Currently there are some issues that need to be resolved to support Windows.  Some reference material can be found here; [Running Docker in Docker on Windows (Linux containers)](https://tomgregory.com/running-docker-in-docker-on-windows/).


Next Steps (as I see them):
1. Getting `indy-test-automation` to build/run locally using the [system/docker/prepare.sh](https://github.com/hyperledger/indy-test-automation/blob/main/system/docker/prepare.sh) and [system/docker/run.sh](https://github.com/hyperledger/indy-test-automation/blob/main/system/docker/run.sh) scripts, and the documentation in the [system/docker/README.md](https://github.com/hyperledger/indy-test-automation/blob/main/system/docker/README.md).  This will enable local development to be performed on `indy-test`automation` and help speed up the development process.
2. Update the associated Dockerfile(s) to support conditional installation of the `sovrin` packages; `sovrin`, `sovtoken`, and `sovtokenfees` for the node, and `libsovtoken` for the client.  This may require separate docker files in order to perform properly.
3. Determine which unit tests in `indy-node` rely on either the `sovrin` or the `token-plugin` packages and move those to the appropriate repo leaving only `indy-node` specific tests.
4. Later, as a separate task, refactor `indy-test-automation` to generically support testing of `indy-node` based packages.

cc @udosson, @pSchlarb

**Comment by WadeBarnes** [comment]
The main concern expressed by this issue has been resolved by https://github.com/hyperledger/indy-test-automation/pull/109
